development:
  adapter: mysql2
  database: sidekiq_sample 
  pool: 120
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin

test:
  adapter: mysql2
  database: sidekiq_sample
  pool: 150
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin

production:
  adapter: mysql2
  database: sidekiq_sample
  pool: 150
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin
